-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    employee_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.employers
(
    employers_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    company_name character varying(50) NOT NULL,
    website_address character varying(50) NOT NULL,
    phone_number character varying(15) NOT NULL,
    is_activate boolean NOT NULL,
    PRIMARY KEY (employers_id)
);

CREATE TABLE public.candidates
(
    candidate_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    identity_number character varying(11) NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (candidate_id)
);

CREATE TABLE public.activation_codes
(
    activation_code_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    activation_code character varying(25) NOT NULL,
    send_date date NOT NULL,
    is_confirm boolean NOT NULL,
    confirm_date date,
    PRIMARY KEY (activation_code_id)
);

CREATE TABLE public.employer_activates
(
    employer_activate_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    confirmed_employee_id integer NOT NULL,
    is_confirm boolean NOT NULL,
    confirm_date date NOT NULL,
    PRIMARY KEY (employer_activate_id)
);

CREATE TABLE public.job_titles
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    title character varying(50) NOT NULL,
    create_date date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employees (employee_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employers (employers_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.candidates (candidate_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_codes (activation_code_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.employer_activates (employer_activate_id)
    NOT VALID;

END;